// Regenerates client/src/theme.css from the DEFAULT_PRESET_NAME in presets.ts.
// Run: npm run gen-theme (from the client/ directory)
import { writeFileSync } from "fs";
import { join } from "path";
import { PRESETS, DEFAULT_PRESET_NAME } from "../client/src/presets";

const preset = PRESETS.find((p) => p.name === DEFAULT_PRESET_NAME);
if (!preset) {
  console.error(`Preset "${DEFAULT_PRESET_NAME}" not found in PRESETS`);
  process.exit(1);
}

const vars = Object.entries(preset.vars)
  .map(([k, v]) => `  ${k}: ${v};`)
  .join("\n");

const css = `/* Default palette — ${DEFAULT_PRESET_NAME}.
   Generated by scripts/gen-default-theme.ts — do not edit by hand.
   To change the default: update DEFAULT_PRESET_NAME in client/src/presets.ts
   then run \`npm run gen-theme\` from the client/ directory. */
:root {
${vars}
}
`;

const out = join(import.meta.dirname, "../client/src/theme.css");
writeFileSync(out, css, "utf8");
console.log(`theme.css updated to "${DEFAULT_PRESET_NAME}"`);
