import { writeFileSync } from "fs";
import { join } from "path";

const GUESSES_URL =
  "https://raw.githubusercontent.com/tabatkins/wordle-list/main/words";
const FREQUENCY_URL =
  "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_50k.txt";
const NAMES_URL =
  "https://raw.githubusercontent.com/smashew/NameDatabases/master/NamesDatabases/first%20names/us.txt";

const ANSWER_COUNT = 2500;

async function fetchWords(url: string): Promise<string[]> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();
  return text.trim().split("\n").map((w) => w.trim().toLowerCase()).filter((w) => w.length === 5);
}

async function fetchFrequencies(url: string): Promise<Map<string, number>> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();
  const map = new Map<string, number>();
  for (const line of text.trim().split("\n")) {
    const [word, count] = line.trim().split(" ");
    if (word && count) map.set(word.toLowerCase(), parseInt(count, 10));
  }
  return map;
}

async function fetchNames(url: string): Promise<Set<string>> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();
  const names = new Set<string>();
  for (const line of text.trim().split("\n")) {
    const name = line.trim().toLowerCase();
    if (name.length === 5) names.add(name);
  }
  return names;
}

async function main() {
  console.log("Fetching valid guesses...");
  const guesses = await fetchWords(GUESSES_URL);
  console.log(`  ${guesses.length} valid guesses`);

  console.log("Fetching word frequencies...");
  const frequencies = await fetchFrequencies(FREQUENCY_URL);
  console.log(`  ${frequencies.size} words in frequency list`);

  console.log("Fetching names list...");
  const names = await fetchNames(NAMES_URL);
  console.log(`  ${names.size} 5-letter names to exclude from answers`);

  const answers = guesses
    .filter((w) => frequencies.has(w) && !names.has(w))
    .sort((a, b) => (frequencies.get(b) ?? 0) - (frequencies.get(a) ?? 0))
    .slice(0, ANSWER_COUNT);
  console.log(`  ${answers.length} answers (top ${ANSWER_COUNT} by frequency)`);

  const answerSet = new Set(answers);
  const extraGuesses = guesses.filter((w) => !answerSet.has(w));

  function formatArray(words: string[], exported: string): string {
    const chunks: string[] = [];
    for (let i = 0; i < words.length; i += 10) {
      chunks.push('  "' + words.slice(i, i + 10).join('", "') + '"');
    }
    return `${exported} = [\n${chunks.join(",\n")},\n]`;
  }

  const out = [
    `// Generated by scripts/fetch-words.ts — do not edit manually`,
    `// Answers: ${answers.length} (top by frequency), Valid guesses: ${guesses.length}`,
    ``,
    `export const ANSWERS: string[] ${formatArray(answers, "")}`,
    ``,
    `export const VALID_GUESSES = new Set<string>([`,
    `  ...ANSWERS,`,
    ...extraGuesses.reduce<string[]>((acc, _, i) => {
      if (i % 10 === 0) acc.push('  "' + extraGuesses.slice(i, i + 10).join('", "') + '",');
      return acc;
    }, []),
    `]);`,
  ].join("\n");

  const outPath = join(import.meta.dirname, "..", "words.ts");
  writeFileSync(outPath, out, "utf8");
  console.log(`Written to ${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
