import { writeFileSync } from "fs";
import { join } from "path";

const GUESSES_URL =
  "https://raw.githubusercontent.com/tabatkins/wordle-list/main/words";

async function fetchWords(url: string): Promise<string[]> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();
  return text.trim().split("\n").map((w) => w.trim().toLowerCase()).filter((w) => w.length === 5);
}

async function main() {
  console.log("Fetching valid guesses...");
  const guesses = await fetchWords(GUESSES_URL);
  console.log(`  ${guesses.length} valid guesses`);

  const answers = guesses;
  const extraGuesses: string[] = [];

  function formatArray(name: string, words: string[], exported: string): string {
    const chunks: string[] = [];
    for (let i = 0; i < words.length; i += 10) {
      chunks.push('  "' + words.slice(i, i + 10).join('", "') + '"');
    }
    return `${exported} = [\n${chunks.join(",\n")},\n]`;
  }

  const out = [
    `// Generated by scripts/fetch-words.ts — do not edit manually`,
    `// Answers: ${answers.length} (same as valid guesses)`,
    ``,
    `export const ANSWERS: string[] ${formatArray("ANSWERS", answers, "")}`,
    ``,
    `export const VALID_GUESSES = new Set<string>([`,
    `  ...ANSWERS,`,
    ...extraGuesses.reduce<string[]>((acc, _, i) => {
      if (i % 10 === 0) acc.push('  "' + extraGuesses.slice(i, i + 10).join('", "') + '",');
      return acc;
    }, []),
    `]);`,
  ].join("\n");

  const outPath = join(import.meta.dirname, "..", "words.ts");
  writeFileSync(outPath, out, "utf8");
  console.log(`Written to ${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
